name: Build macOS App

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller customtkinter

      - name: Create dist folder
        run: mkdir -p dist

      - name: Build macOS app
        run: |
          pyinstaller --onefile --windowed \
            --name ShutdownScheduler main.py

      - name: Upload macOS build to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: dist/ShutdownScheduler
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}